spring:
  datasource:
    url: jdbc:h2:mem:userdb;DB_CLOSE_DELAY=-1;MODE=MYSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always
mybatis:
  mapper-locations: classpath:/mapper/*.xml
mybatis-plus:
  configuration:
    type-aliases-package: com.example.xiaohongshu_microservices.domain
    mapper-locations: classpath:/mapper/*.xml
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
server:
  port: 8080

logging:
  level:
    com.yourorg: debug