openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:8080
  description: Generated server url
tags:
- name: 用户管理
  description: 用户基础信息增删改查
paths:
  /user/{userId}:
    get:
      tags:
      - 用户管理
      summary: 根据用户ID查询用户信息
      operationId: getById
      parameters:
      - name: userId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Users"
    put:
      tags:
      - 用户管理
      summary: 更新用户邮箱
      operationId: updateEmail
      parameters:
      - name: userId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      - name: newEmail
        in: query
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Users"
  /user/createUser:
    post:
      tags:
      - 用户管理
      summary: 创建新用户
      operationId: createUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Users"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Users"
components:
  schemas:
    Users:
      type: object
      properties:
        id:
          type: integer
          format: int64
        username:
          type: string
        password:
          type: string
        email:
          type: string
        createdAt:
          type: string
          format: date-time
